services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WITH_DEV: 1
    ports:
      - 50051:50051
    volumes:
      - .:/app
    command: python -m src.entrypoint.grpc_server
    env_file:
      - .env.dev
