# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: recommend_api/v1/recommend_api.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'recommend_api/v1/recommend_api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$recommend_api/v1/recommend_api.proto\x12\x10recommend_api.v1\"-\n\x10RecommendRequest\x12\x19\n\x08item_ids\x18\x01 \x03(\x05R\x07itemIds\".\n\x11RecommendResponse\x12\x19\n\x08item_ids\x18\x01 \x03(\x05R\x07itemIds2j\n\x12RecommenderService\x12T\n\tRecommend\x12\".recommend_api.v1.RecommendRequest\x1a#.recommend_api.v1.RecommendResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recommend_api.v1.recommend_api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RECOMMENDREQUEST']._serialized_start=58
  _globals['_RECOMMENDREQUEST']._serialized_end=103
  _globals['_RECOMMENDRESPONSE']._serialized_start=105
  _globals['_RECOMMENDRESPONSE']._serialized_end=151
  _globals['_RECOMMENDERSERVICE']._serialized_start=153
  _globals['_RECOMMENDERSERVICE']._serialized_end=259
# @@protoc_insertion_point(module_scope)
